---
stages:
- name: INITIALIZE-REPO
  inputs:
  - type: git
    service: ${SAMPLE_REPO}
    branch: master    
  properties:
  - name: RUNTIME-BRANCH
    value: add-sc-runtime
    type: text
  - name: REPO-KEY
    value: NO-DEFAULT-VALUE
    type: secure
  jobs:
  - name: Add Runtime
    type: shell
    script: |
    #!/bin/bash
    # If you ever repeat these steps, this make generate a message saying the remote already exists.
    git_repo="${$MANIFEST_REPO/KEY/$REPO_KEY}"
    $ git remote add manifest-runtime-production ${git_repo}

    # we want to check into a dedicated branch
    $ git checkout -b ${RUNTIME-BRANCH}

    # git subtree add triggers a background commit if there are changes available
    $ git subtree add --prefix=manifest manifest-runtime-production master -m "Add manifest-runtime-production content" --squash

    # push into dedicated branch
    $ git push origin ${RUNTIME-BRANCH}
  - name: Create manifest template
    type: shell
    script: |
    #!/bin/bash

    cd manifest || echo "Manifest directory missing"; exit 1
    make generate || echo "Make failed"; exit 1