---
stages:
- name: INITIALIZE-REPO
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
    dir_name: null
  properties:
  - name: RUNTIME_BRANCH
    value: add-sc-runtime
    type: text
  - name: REPO_KEY
    value: ${RUNTIME_REPO_KEY}
    type: secure
  - name: RUNTIME_REPO
    value: ${RUNTIME_REPO}
    type: text
  - name: GIT_USER
    value: ${GIT_USER}
    type: text
  jobs:
  - name: Add Runtime
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |-
      #!/bin/bash

      set -x      

      git config user.email "${GIT_USER}@ibm.com"
      git config user.name "${GIT_USER}"

      # Add deploy key to GIT repo url by replacing // with //<key>@
      git_repo="${RUNTIME_REPO/\/\//\/\/${REPO_KEY}@}"
      git remote add manifest-runtime-production ${git_repo}

      # we want to check into a dedicated branch
      git checkout -b ${RUNTIME_BRANCH}

      # git subtree add triggers a background commit if there are changes available
      git subtree add --prefix=manifest manifest-runtime-production master -m "Add manifest-runtime-production content" --squash

      # push into dedicated branch
      git push origin ${RUNTIME_BRANCH}
- name: GENERATE-MANIFEST
  inputs:
  - type: git
    branch: add-sc-runtime
    service: ${SAMPLE_REPO}
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: GIT_USER
    value: ${GIT_USER}
    type: text
  jobs:
  - name: Generate manifest
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |-
      #!/bin/bash

      set -x

      git config user.email "${GIT_USER}@ibm.com"
      git config user.name "${GIT_USER}"

      cd manifest
      make generate
  - name: Create and register manifest
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |-
      #!/bin/bash

      set -x

      rootdir=${PWD}
      manifestdir=manifest/res
      manifest_template=servicemanifest.json

      cd ${manifestdir}
      node > out_${manifest_template} <<EOF

      // Read data
      var manifest = require('./${manifest_template}');

      // Edit the required fields
      manifest.service_name = 'service-name';
      manifest.component_name = 'component-name';
      manifest.cname = '\$env(\'CNAME\')';
      manifest.ctype = 'public';
      manifest.region = '\$env(\'REGION\')';
      manifest.resource_type = 'cf-application';
      manifest.tenancy = 'shared';
      manifest.pager_duty = 'escalation url';
      manifest.team_email = 'team_email';
      manifest.bailey_url = 'bailey-url';
      manifest.bailey_project = 'bailey-project';
      manifest.repo_url = 'git-repo';
      manifest.bluemix_account = '';

      // Remove invalid data
      manifest.component_instance = '';
      manifest.scope = '';
      manifest.resource = '';
      manifest.softlayer_account = '';
      manifest.softlayer_account_api_key_id = '';
      manifest.bluemix_account_api_key_id = '';
      manifest.security_status_url = '';
      manifest.static_sec_analyze_url = '';
      manifest.customer_ticket_repo_url = '';
      manifest.runbook_repo_url = '';
      manifest.continuity_plan_url = '';


      // Output data
      console.log(JSON.stringify(manifest, null, 2));
      EOF

      # Move the file to checkin
      mv ${manifestdir}/out_${manifest_template} ${manifestdir}/${manifest_template}

      # Add the updated manifest
      cd ${rootdir}
      git add ${manifestdir}/servicemanifest.json
      git commit -m "Adding Service Manifest file"
      git push origin ${RUNTIME_BRANCH}
  - name: Register manifest
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |-
      #!/bin/bash

      set -x

      # Change to manifest directory
      cd manifest

      # Validate the service manifest
      make validate || exit 1

      # Cleanup possible leftovers from previous builds
      make clean || exit 1

      # Build the manifest library
      make || exit 1

      # Register/Update your service component with the Service Registry
      make package || exit 1